/******************************************************************************
 * Autogenerated by keyboard_compares.py BANK0 1024 0.995 8.22 3.90 2.20 0.998
 ******************************************************************************/
#define BANK0_NUM_SWITCHES 4
const int BANK0_ADC_VALUES[] = {
	   0, // Switches: [    ]
	 511, // Switches: [   o]
	 318, // Switches: [  o ]
	 605, // Switches: [  oo]
	 208, // Switches: [ o  ]
	 569, // Switches: [ o o]
	 424, // Switches: [ oo ]
	 645, // Switches: [ ooo]
	 110, // Switches: [o   ]
	 540, // Switches: [o  o]
	 373, // Switches: [o o ]
	 625, // Switches: [o oo]
	 279, // Switches: [oo  ]
	 592, // Switches: [oo o]
	 463, // Switches: [ooo ]
	 661, // Switches: [oooo]
};

