/******************************************************************************
 * Autogenerated by keyboard_compares.py BANK1 1024 0.984 8.24 3.91 2.19 1.000
 ******************************************************************************/
#define BANK1_NUM_SWITCHES 4
const int BANK1_ADC_VALUES[] = {
	   0, // Switches: [    ]
	 507, // Switches: [   o]
	 317, // Switches: [  o ]
	 603, // Switches: [  oo]
	 205, // Switches: [ o  ]
	 565, // Switches: [ o o]
	 421, // Switches: [ oo ]
	 642, // Switches: [ ooo]
	 109, // Switches: [o   ]
	 537, // Switches: [o  o]
	 371, // Switches: [o o ]
	 622, // Switches: [o oo]
	 277, // Switches: [oo  ]
	 589, // Switches: [oo o]
	 461, // Switches: [ooo ]
	 658, // Switches: [oooo]
};

