/******************************************************************************
 * Autogenerated by keyboard_compares.py BANK2 1024 0.986 8.26 3.87 2.19 0.998
 ******************************************************************************/
#define BANK2_NUM_SWITCHES 4
const int BANK2_ADC_VALUES[] = {
	   0, // Switches: [    ]
	 508, // Switches: [   o]
	 317, // Switches: [  o ]
	 604, // Switches: [  oo]
	 207, // Switches: [ o  ]
	 567, // Switches: [ o o]
	 423, // Switches: [ oo ]
	 643, // Switches: [ ooo]
	 109, // Switches: [o   ]
	 538, // Switches: [o  o]
	 371, // Switches: [o o ]
	 623, // Switches: [o oo]
	 278, // Switches: [oo  ]
	 590, // Switches: [oo o]
	 462, // Switches: [ooo ]
	 659, // Switches: [oooo]
};

